apiVersion: v1
kind: Service
metadata:
  name: techtrends
  namespace: {{ .Values.namespace.name }}
spec:
  ports:
  - port: {{ .Values.service.port }}
    protocol: {{ .Values.service.protocol }}
    targetPort: {{ if not .Values.service.targetPort }} {{ .Values.service.port }}{{ end }}
  type: {{ .Values.service.type }}
